name: Go Test

on:
    push:
        branches:
            - "dev"

jobs:
    build:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v4
            - name: Setup Go environment
              uses: actions/setup-go@v5.0.0
            - name: Get dependencies
              run: go get -v -t -d ./...
            - name: Run tests
              run: go test -v ./...
            - name: Add Go binaries to PATH
              run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
            - name: Install Swag
              run: go install github.com/swaggo/swag/cmd/swag@latest
            - name: Generate Swagger documentation
              run: swag init --parseDependency -d ./internal/server -g ../../cmd/api/main.go
            - name: Commit Swagger documentation
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git checkout -b docs-update-${GITHUB_SHA}
                  git pull origin docs-update-${GITHUB_SHA} --allow-unrelated-histories || true
                  git add docs/
                  git commit -m "Update Swagger documentation" || echo "No changes to commit"
                  git push origin docs-update-${GITHUB_SHA}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: dev
                  title: Update Swagger documentation
                  body: |
                    This PR updates the Swagger documentation.
            
