name: Go Test

on:
    push:
        branches:
            - "*"

jobs:
    build:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v4
            - name: Setup Go environment
              uses: actions/setup-go@v5.0.0
            - name: Get dependencies
              run: go get -v -t -d ./...
            - name: Run tests
              run: go test -v ./...
